export const FETCH_CHAR_REUEST = 'FETCH_CHAR_REUEST';
export const FETCH_CHAR_SUCCESS = 'FETCH_CHAR_SUCCESS';
export const FETCH_CHAR_FAILURE = 'FETCH_CHAR_FAILURE';
export const FETCH_CHAR_RELATED = 'FETCH_CHAR_RELATED';

export const FETCH_FILM_REUEST = 'FETCH_FILM_REUEST';
export const FETCH_FILM_SUCCESS = 'FETCH_FILM_SUCCESS';
export const FETCH_FILM_FAILURE = 'FETCH_FILM_FAILURE';
export const FETCH_FILM_RELATED = 'FETCH_FILM_RELATED';

export const FETCH_PLANET_REUEST = 'FETCH_PLANET_REUEST';
export const FETCH_PLANET_SUCCESS = 'FETCH_PLANET_SUCCESS';
export const FETCH_PLANET_FAILURE = 'FETCH_PLANET_FAILURE';
export const FETCH_PLANET_RELATED = 'FETCH_PLANET_RELATED';

export const FETCH_SPECIES_REUEST = 'FETCH_SPECIES_REUEST';
export const FETCH_SPECIES_SUCCESS = 'FETCH_SPECIES_SUCCESS';
export const FETCH_SPECIES_FAILURE = 'FETCH_SPECIES_FAILURE';
export const FETCH_SPECIES_RELATED = 'FETCH_SPECIES_RELATED';

export const FETCH_STARSHIP_REUEST = 'FETCH_STARSHIP_REUEST';
export const FETCH_STARSHIP_SUCCESS = 'FETCH_STARSHIP_SUCCESS';
export const FETCH_STARSHIP_FAILURE = 'FETCH_STARSHIP_FAILURE';
export const FETCH_STARSHIP_RELATED = 'FETCH_STARSHIP_RELATED';

export const FETCH_VEHICLE_REUEST = 'FETCH_VEHICLE_REUEST';
export const FETCH_VEHICLE_SUCCESS = 'FETCH_VEHICLE_SUCCESS';
export const FETCH_VEHICLE_FAILURE = 'FETCH_VEHICLE_FAILURE';
export const FETCH_VEHICLE_RELATED = 'FETCH_VEHICLE_RELATED';

export const FETCH_API_REUEST = 'FETCH_API_REUEST';
export const FETCH_API_SUCCESS = 'FETCH_API_SUCCESS';
export const FETCH_API_FAILURE = 'FETCH_API_FAILURE';
export const FETCH_API_RELATED = 'FETCH_API_RELATED';